name: Generate Genres - Dev

on:
  pull_request:
    types: closed 
    branches:
    - main
    - dev

permissions:
  contents: read

jobs:
  populate_data:
    name: poplulate data to mysql table genres
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate genres
      env:
        AIVEN_DB_HOST: ${{ secrets.AIVEN_DB_HOST }}
        AIVEN_DB_PASS: ${{ secrets.AIVEN_DB_PASS }}
        AIVEN_DB_PORT: ${{ secrets.AIVEN_DB_PORT }}
        AIVEN_DB_USER: ${{ secrets.AIVEN_DB_USER }}
        FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}
        FILEBASE_KEY: ${{ secrets.FILEBASE_KEY }}
        FILEBASE_SECRET: ${{ secrets.FILEBASE_SECRET }}
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        DB: ${{ vars.DB }}
        S3_ENDPOINT_URL: ${{ vars.S3_ENDPOINT_URL }}
      run: |
        python create_or_replace_genres.py
