name: Generate Movie Details - Dev

on:
  pull_request:
    types: closed 
    branches:
    - dev

permissions:
  contents: read
  id-token: write

jobs:
  populate_data:
    name: poplulate data to mysql table movie_details
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v4
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/737871976843/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
        service_account: "mep-service-account@myentertainmentproject.iam.gserviceaccount.com"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate movie_details
      env:
        AIVEN_DB_HOST: ${{ secrets.AIVEN_DB_HOST }}
        AIVEN_DB_PASS: ${{ secrets.AIVEN_DB_PASS }}
        AIVEN_DB_PORT: ${{ secrets.AIVEN_DB_PORT }}
        AIVEN_DB_USER: ${{ secrets.AIVEN_DB_USER }}
        FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}
        FILEBASE_KEY: ${{ secrets.FILEBASE_KEY }}
        FILEBASE_SECRET: ${{ secrets.FILEBASE_SECRET }}
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        DB: ${{ vars.DB }}
        S3_ENDPOINT_URL: ${{ vars.S3_ENDPOINT_URL }}
      run: |
        python create_or_replace_movie_details.py
