name: Generate Movie Details - Dev

on:
  pull_request:
    types: closed 
    branches:
    - main
    - dev

permissions:
  contents: read

jobs:
  populate_data:
    name: poplulate data to mysql table movie_details
    runs-on: ubuntu-latest
    environment: Dev 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate movie_details
      run: |
        python create_or_replace_movie_details.py
